version: '2'
services:
  freyr:
    restart: always
    image: golang
    volumes:
      - $GOPATH/src/:/go/src/
      - ./:/go/src/github.com/serdmanczyk/freyr/
    working_dir: /go/src/github.com/serdmanczyk/freyr/
    command: go test ./... -tags=integration
    links:
      - postgres
    depends_on:
      - postgres
  postgres:
    build: 
      context: ./postgres/
    image: postgres:9.4
    volumes:
      - ./postgres/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
