version: '2'
services:
  gardensparkdev:
    restart: always
    image: serdmanczyk/gardensparkdev
    build: 
      context: .
      dockerfile: ./run.Dockerfile
    env_file: .env
    links:
      - gspkpostgres
    depends_on:
      - gspkpostgres
    ports:
      - "8080:8080"
  gspkpostgres:
    restart: always
    build: 
      context: ./postgres/
    image: serdmanczyk/gspkpostgres
    env_file: ./postgres/.env
