version: '2'
services:
  nginx:
    image: gspknginx
    build: 
      context: ./nginx/
    ports:
      - "8080:80"
      - "8443:443"
    links:
      - gardenspark
  gardenspark:
    restart: always
    image: serdmanczyk/gardenspark
    build: 
      context: .
      dockerfile: ./static.Dockerfile
    env_file: .env
    links:
      - gspkpostgres
    depends_on:
      - gspkpostgres
  gspkpostgres:
    restart: always
    build: 
      context: ./postgres/
    image: serdmanczyk/gspkpostgres
    env_file: ./postgres/.env
