version: '2'
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/conf:/etc/nginx/
      - ./nginx/static:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    links:
      - freyr
  freyr:
    restart: always
    image: golang
    volumes:
      - $GOPATH/src/:/go/src/
      - ./:/go/src/github.com/serdmanczyk/freyr/
    working_dir: /go/src/github.com/serdmanczyk/freyr/
    command: go run main.go
    env_file: .env
    links:
      - postgres
  postgres:
    restart: always
    image: postgres:9.4
    volumes:
      - ./postgres/:/docker-entrypoint-initdb.d/
    env_file: ./postgres/.env
